name: memory_share
description: memory_share mobile app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  arcore_flutter_plugin: ^0.0.10

  google_maps_flutter: ^2.0.6
  geolocator: ^7.2.0+1

  flutter_config: ^2.0.0

  image_picker: ^0.8.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/
