name: memory_share
description: memory_share mobile app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  arcore_flutter_plugin: ^0.0.10

  flutter_riverpod: ^0.14.0+3
  state_notifier: ^0.7.0
  freezed_annotation: ^0.14.2

  google_maps_flutter: ^2.0.6
  location: ^4.3.0

  flutter_config: ^2.0.0

  image_picker: ^0.8.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  freezed: ^0.14.2

flutter:

  uses-material-design: true

  assets:
    - assets/
